name: my first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List dir & view readme
      run: | 
        echo Welcome to the actions
        ls
        cat README.md