name: generate ascii art work
on: push
jobs:
  ascii_jobs: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: list files
      run: ls -ltra

    - name: executing schell script
      run: |
           chmod +x .github/ascii-script.sh
           ./github/ascii-script.sh
